###
GET http://localhost:3000/exams

###
GET http://localhost:3000/exams/870102/questions

###
GET http://localhost:3000/exams/870101/results

###
GET http://localhost:3000/universities

###
GET http://localhost:3000/universities/100105

###
GET http://localhost:3000/registration

###
GET http://localhost:3000/filter-univ?type_univ=Swasta&accreditation_univ=Unggul&scope=SOSHUM&major_name=Analisis%20Keuangan&accreditation_major=A

###
GET http://localhost:3000/filter-univ?type_univ=Negeri&accreditation_univ=Unggul&scope=SAINTEK&major_name=Teknologi%20Informasi&accreditation_major=A
  
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Pram",
  "email": "pramudhita@gmail.com",
  "password": "neomuyeppo"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "pramudhita@gmail.com",
  "password": "neomuyeppo"
}
